# Generated by Django 4.1 on 2022-08-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('purchaser', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
